//===-- Implementation header for log1pf16 ----------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIBC_SRC___SUPPORT_MATH_LOG1PF16_H
#define LLVM_LIBC_SRC___SUPPORT_MATH_LOG1PF16_H

#include "include/llvm-libc-macros/float16-macros.h"

// Add guard later

#include "exp10_float16_constants.h"
#include "expxf16_utils.h"
#include "hdr/errno_macros.h"
#include "hdr/fenv_macros.h"
#include "src/__support/FPUtil/FEnvImpl.h"
#include "src/__support/FPUtil/FPBits.h"
#include "src/__support/FPUtil/PolyEval.h"
#include "src/__support/FPUtil/cast.h"
#include "src/__support/FPUtil/except_value_utils.h"
#include "src/__support/FPUtil/multiply_add.h"
#include "src/__support/common.h"
#include "src/__support/macros/config.h"
#include "src/__support/macros/optimization.h"
#include "src/__support/macros/properties/cpu_features.h"

namespace LIBC_NAMESPACE_DECL {

namespace math {

LIBC_INLINE float16 log1pf16(float16 x) {
/*
Points to consider near x = -1 , 0 
Domain (1+x)>0
        x>-1
*/

/* 8000 = -0
   7000 = +0
   7C00 = +INF ( 0 11111 0000000000)
   FC00 = -INF 
   3C00 = +1
   BC00 = -1
*/
  using namespace math::expxf16_internal;
  using FPBits = fputil::FPBits<float16>;
  FPBits x_bits(x);

  uint16_t x_u = x_bits.uintval();
  uint16_t x_abs = x_u & 0x7fffU;

  // If x == +/-0, or x is +/-inf, or x is NaN.
  if (LIBC_UNLIKELY(x_abs <= 0x3000U || x_abs >= 0x7c00U)) {
    // log10p1(NaN) = NaN
    if (x_bits.is_nan()) {
      if (x_bits.is_signaling_nan()) {
        fputil::raise_except_if_required(FE_INVALID);
        return FPBits::quiet_nan().get_val();
      }

      return x;
    }

    // log1p(+/-0) = log(+/-1)  = +/-0
    if (x_abs == 0U)
      return x;

    // log1p(+inf) = +inf
    if (x_u == 0x7c00U)
      return FPBits::inf().get_val();

    // log1p(-inf) = NaN
    if (x_abs >= 0x7c00U) {
      fputil::set_errno_if_required(EDOM);
      fputil::raise_except_if_required(FE_INVALID);
      return FPBits::quiet_nan().get_val();
    }

// When |x| <= 2^-3, use a degree-5 minimax polynomial directly in x.
    //
    // For y = 1+x near 1, the table-based range reduction (m*ln(2) + ln(F[f]))
    // suffers catastrophic cancellation. Computing ln(1+x) directly avoids this.
    //
    // Generated by Sollya:
    //   > display = hexadecimal;
    //   > Q = fpminimax(log(1 + x), [|1, 2, 3, 4, 5|], [|SG...|],
    //                   [-2^-3, 2^-3]);
    //   > Q;
    //   > dirtyinfnorm((log(1 + x) - Q) / log(1 + x), [-2^-3, 2^-3]);
    //
    // TODO: replace coefficients below with Sollya output, and fill in
    //       the dirtyinfnorm result in the comment above once generated.
    if (x_abs <= 0x3000U) {
      float xf = x;
      return fputil::cast<float16>(
          xf * fputil::polyeval(xf,
              /* c1 */ 0x1.000000p+0f,    // TODO: Sollya
              /* c2 */ -0x1.000000p-1f,   // TODO: Sollya
              /* c3 */ 0x1.555556p-2f,    // TODO: Sollya
              /* c4 */ -0x1.000000p-2f,   // TODO: Sollya
              /* c5 */ 0x1.99999ap-3f));  // TODO: Sollya
    }
    
  }
} // namespace math
} // namespace LIBC_NAMESPACE_DECL


#endif // LLVM_LIBC_SRC___SUPPORT_MATH_LOG1PF16_H
